# load nginx 
FROM nginx

# Copy our code from the current folder to /app inside the container
COPY . /usr/share/nginx/html

VOLUME /usr/share/nginx/html

# Make port 80 available for links and/or publish
EXPOSE 80
